### ISSUE TITLE
Have a patch

### ISSUE THREAD

**Issue by nashant** [m13u/thants-slack-slash#1]
diff --git a/handler.py b/handler.py
index de00ee0..89d6746 100644
--- a/handler.py
+++ b/handler.py
@@ -1,11 +1,11 @@
-"""Responds to a custom Slack slash command that takes two parameters: a prefix
-string and an object (target) string. Truncate the prefix string before the
-first instance of any vowel. Then left-strip the object string until the first
-instance of any vowel (preserve the vowel). Then concatenate the strings and
-return it in-line in Slack.
+"""Responds to a custom Slack slash command that takes any number of strings,
+truncates the first before the first instance of any vowel then left-strips
+the next string until the first instance of any vowel (preserves the vowel)
+and concatenates the strings. This is done for any number of pairs of words,
+then joins them all with ' ' and returns it in-line in Slack.
 
 Usage:
-/slack_command_name prefix_string object_string"""
+/slack_command_name arg1 arg2 arg3 arg4"""
 
 import json
 import re
@@ -29,19 +29,27 @@ def validate_token(request_slack_token):
     else:
         raise ValueError
 
-def string_devoweler(input_string):
-    """Return a substring that has all the characters up to (but not including)
-    the first instance of any vowel"""
-    # Always preserve the first letter, even if it's a vowel, so exclude it from the substitution
-    string_to_disemvowel = input_string[1:]
-    # re.split returns an array, not a string, so we have to convert it back into a string
-    output_array = re.split('[AEIOU]', string_to_disemvowel, maxsplit=1, flags=re.IGNORECASE)[0]
-    # Add the first letter back in and concatenate it with the devoweled-chomped string
-    output_string = input_string[:1] + ''.join(output_array)
-    return output_string
+def get_start(str):
+    """Return the string up to (but not including) the first vowel after a
+    consonant."""
+    str = list(str.lower())
+    out = ''
+    while str[0] in 'aeiou':
+        out += str.pop(0)
+    while not str[0] in 'aeiou':
+        out += str.pop(0)
+
+    if out[-1] == 'q':
+        out += 'u'
+    return out
+
+def get_end(str):
+    """Return the string after (and including) the first vowel."""
+    str = str.lower()
+    return ''.join(re.split('([aeiou])', str, maxsplit=1)[1:])
 
 def string_transformer(event, context):
-    """Handle the two incoming strings sent from a custom Slack slash command,
+    """Handle the incoming strings sent from a custom Slack slash command,
     modify and concatenate the strings and return it in-line in Slack."""
     try:
         request_data = parse_input(event['body'])
@@ -63,21 +71,20 @@ def string_transformer(event, context):
             "body": "{}",
         }
 
-    request_text = request_data['text']
-    prefix_string = request_text.split(' ', 1)[0]
-    object_string = request_text.split(' ', 1)[1]
+    strings = request_data['text'].split(' ')
+    out = ''
 
-    devoweled_prefix_string = string_devoweler(prefix_string)
-    # Strip letters from the object string until we hit our first vowel
-    string_to_delete_from_object = string_devoweler(object_string)
-    devoweled_object_string = re.sub(string_to_delete_from_object, '', object_string, 1)
+    # Add pairs of merged strings to the output
+    while len(strings) > 1:
+        output += '{0}{1}'.format(get_start(strings.pop(0)), get_end(strings.pop(0)))
 
-    # Ellide/Concatenate the strings
-    concatenated_string = devoweled_prefix_string.title() + devoweled_object_string.lower()
+    # Add a trailing spare word if there is one
+    if len(strings) > 0:
+        out += strings[0]
 
     response = {
         "response_type": "in_channel",
-        "text": concatenated_string,
+        "text": out.capitalize(),
     }
 
     return {

**Comment by nashant** [comment]
Hahaha! That did not do what I wanted

**Comment by nashant** [comment]
```
diff --git a/handler.py b/handler.py
index de00ee0..89d6746 100644
--- a/handler.py
+++ b/handler.py
@@ -1,11 +1,11 @@
-"""Responds to a custom Slack slash command that takes two parameters: a prefix
-string and an object (target) string. Truncate the prefix string before the
-first instance of any vowel. Then left-strip the object string until the first
-instance of any vowel (preserve the vowel). Then concatenate the strings and
-return it in-line in Slack.
+"""Responds to a custom Slack slash command that takes any number of strings,
+truncates the first before the first instance of any vowel then left-strips
+the next string until the first instance of any vowel (preserves the vowel)
+and concatenates the strings. This is done for any number of pairs of words,
+then joins them all with ' ' and returns it in-line in Slack.
 
 Usage:
-/slack_command_name prefix_string object_string"""
+/slack_command_name arg1 arg2 arg3 arg4"""
 
 import json
 import re
@@ -29,19 +29,27 @@ def validate_token(request_slack_token):
     else:
         raise ValueError
 
-def string_devoweler(input_string):
-    """Return a substring that has all the characters up to (but not including)
-    the first instance of any vowel"""
-    # Always preserve the first letter, even if it's a vowel, so exclude it from the substitution
-    string_to_disemvowel = input_string[1:]
-    # re.split returns an array, not a string, so we have to convert it back into a string
-    output_array = re.split('[AEIOU]', string_to_disemvowel, maxsplit=1, flags=re.IGNORECASE)[0]
-    # Add the first letter back in and concatenate it with the devoweled-chomped string
-    output_string = input_string[:1] + ''.join(output_array)
-    return output_string
+def get_start(str):
+    """Return the string up to (but not including) the first vowel after a
+    consonant."""
+    str = list(str.lower())
+    out = ''
+    while len(str) > 0 and str[0] in 'aeiou:':
+        out += str.pop(0)
+    while len(str) > 0 and not str[0] in 'aeiou':
+        out += str.pop(0)
+
+    if out[-1] == 'q':
+        out += 'u'
+    return out
+
+def get_end(str):
+    """Return the string after (and including) the first vowel."""
+    str = str.lower()
+    return ''.join(re.split('([aeiou])', str, maxsplit=1)[1:])
 
 def string_transformer(event, context):
-    """Handle the two incoming strings sent from a custom Slack slash command,
+    """Handle the incoming strings sent from a custom Slack slash command,
     modify and concatenate the strings and return it in-line in Slack."""
     try:
         request_data = parse_input(event['body'])
@@ -63,21 +71,20 @@ def string_transformer(event, context):
             "body": "{}",
         }
 
-    request_text = request_data['text']
-    prefix_string = request_text.split(' ', 1)[0]
-    object_string = request_text.split(' ', 1)[1]
+    strings = request_data['text'].split(' ')
+    out = ''
 
-    devoweled_prefix_string = string_devoweler(prefix_string)
-    # Strip letters from the object string until we hit our first vowel
-    string_to_delete_from_object = string_devoweler(object_string)
-    devoweled_object_string = re.sub(string_to_delete_from_object, '', object_string, 1)
+    # Add pairs of merged strings to the output
+    while len(strings) > 1:
+        output += '{0}{1} '.format(get_start(strings.pop(0)), get_end(strings.pop(0)))
 
-    # Ellide/Concatenate the strings
-    concatenated_string = devoweled_prefix_string.title() + devoweled_object_string.lower()
+    # Add a trailing spare word if there is one
+    if len(strings) > 0:
+        out += strings[0]
 
     response = {
         "response_type": "in_channel",
-        "text": concatenated_string,
+        "text": out.capitalize(),
     }
 
     return {
```

**Comment by m13u** [comment]
I've applied your patch to `develop`, but in the future please raise a PR instead.
